version: '3.8'

services:
  # --------------------------------------------------------------------------
  # 1) Infisical Backend (API & Interface Web)
  # --------------------------------------------------------------------------
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    image: infisical/infisical:latest-postgres
    pull_policy: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - "8080:8080"
    networks:
      - traefik
      - infisical
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infisical.rule=Host(`infisical.jeremiealcaraz.com`)"
      - "traefik.http.routers.infisical.entrypoints=websecure"
      - "traefik.http.routers.infisical.tls.certresolver=mytlschallenge"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"

  # --------------------------------------------------------------------------
  # 2) Redis (Cache pour Infisical)
  # --------------------------------------------------------------------------
  redis:
    image: redis
    container_name: infisical-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical
    volumes:
      - redis_data:/data

  # --------------------------------------------------------------------------
  # 3) Base de Données PostgreSQL
  # --------------------------------------------------------------------------
  db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

# --------------------------------------------------------------------------
# 4) Définition des Volumes (Persistance des données)
# --------------------------------------------------------------------------
volumes:
  pg_data:
  redis_data:

# --------------------------------------------------------------------------
# 5) Définition des Réseaux
# --------------------------------------------------------------------------
networks:
  traefik:
    external: true
  infisical:
